=== kellypitts91/XML-XSD-Sports/WebContent/sport.xsd
<?xml version="1.0" ?>

<!-- 
	Author: Kelly Pitts 09098321 
	Sport Schema - First Vocabulary
-->

<!DOCTYPE xml>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:attributeGroup name="sportAttribute" > <!-- named attribute group -->
		<xs:attribute name="id" type="xs:integer" use="required" />
		<xs:attribute name="teamName" type="xs:string" use="required" />
	</xs:attributeGroup>
	<xs:element name="sports">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="sport" minOccurs="1" maxOccurs="unbounded" >
					<xs:complexType>
						<xs:sequence> 
							<xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1" />
							<xs:element name="noOfPlayers" type="xs:integer" minOccurs="1" maxOccurs="1" />
							
							<xs:element name="international" minOccurs="1" maxOccurs="1"> 
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<!--<xs:pattern value="international|national"/>-->
										<xs:enumeration value="international" />
										<xs:enumeration value="national" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						
							<xs:element name="type" minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="indoor|outdoor"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							
							<xs:element name="location" type="lType" minOccurs="1" maxOccurs="1" />
							
							<xs:element name="description" type="xs:string" minOccurs="1" maxOccurs="1" />
						</xs:sequence>
						<xs:attributeGroup ref="sportAttribute" />
						
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="lType"> <!-- named complex type -->
		<xs:sequence>
			<xs:element name="country" type="xs:string" />
			<xs:element name="city" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== kellypitts91/XML-XSD-Sports/WebContent/sport.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!--
	Author: Kelly Pitts 09098321 
	Sport Instance - First Vocabulary
-->

<!DOCTYPE xml>
<sports xmlns:xsi="http://www.w3.org/2001/XMLSchema-Instance" 
		xmlns="http://example.com/sports/ns"
		xsi:schemaLocation="http://example.com/sports/ns sport.xsd">
		
	<sport id="1" teamName="BlackCaps">
		<sportName>Cricket</sportName>
		<noOfPlayers>11</noOfPlayers>
		<international>international</international>
		<type>outdoor</type>
		<location>
			<country>New Zealand</country>
			<city>Auckland</city>
		</location>
		<description>
			The New Zealand cricket team, nicknamed the Black Caps, are the national cricket team 
			representing New Zealand. They played their first Test in 1930 against England in 
			Christchurch, New Zealand, becoming the fifth country to play Test cricket. 
			From 1930 New Zealand had to wait until 1956, more than 26 years, for its first test victory, 
			against the West Indies at Eden Park in Auckland.[3] They played their first ODI in the 1972â€“73 
			season against Pakistan in Christchurch.
			(BlackCaps, Wikipedia)
		</description>
	</sport>
	<sport id="2" teamName="AllBlacks">
		<sportName>Rugby</sportName>
		<noOfPlayers>13</noOfPlayers>
		<international>international</international>
		<type>outdoor</type>
		<location>
			<country>New Zealand</country>
			<city>Auckland</city>
		</location>
		<description>
			The New Zealand national rugby union team, commonly called the All Blacks, represent New Zealand 
			in men's rugby union, which is regarded as the country's national sport.[1] The side has won the 
			last two Rugby World Cups, in 2011 and 2015, as well as the inaugural tournament in 1987. 
			They have a 77% winning record in test match rugby, and are the only international side with a 
			winning record against every opponent. Since their international debut in 1903, they have lost 
			to only five of the 19 nations they have played in test matches.[a] Since the introduction of 
			the World Rugby Rankings in 2003, New Zealand has held the number one ranking longer than all 
			other teams combined.[2] The All Blacks are statistically the best side to have played the game.
			(The All Blacks, Wikipedia)
		</description>
	</sport>
</sports>
